name: Test

on:
  push:

jobs:
  pnpm-7-18:
    runs-on: ubuntu-22.04
    name: PNPM 7.18
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: pnpm install
      - run: pnpm run test

  pnpm-7-19:
    runs-on: ubuntu-22.04
    name: PNPM 7.18
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.19.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: pnpm install
      - run: pnpm run test
